name: carlton
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  cached_network_image: ^3.4.1
  device_info_plus: ^13.2.0
  dio: ^5.10.0
  file_picker: ^12.0.0-beta.1
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^22.0.1
  flutter_svg: ^2.3.0
  get: ^4.7.3
  get_storage: ^2.1.1
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  package_info_plus: ^10.2.0
  path_provider: ^2.1.6
  permission_handler: ^12.0.3
  pinput: ^6.0.2
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  video_player: ^2.12.0
  country_code_picker: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.4

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/videos/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
    - family: The Seasons
      fonts:
       - asset: assets/fonts/The_Seasons_Light.ttf
         weight: 300
       - asset: assets/fonts/The_Seasons_Regular.ttf
         weight: 400
       - asset: assets/fonts/The_Seasons_Bold.ttf
         weight: 700
    - family: Cabinet Grotesk
      fonts:
        - asset: assets/fonts/CabinetGrotesk-Thin.ttf
          weight: 100
        - asset: assets/fonts/CabinetGrotesk-Extralight.ttf
          weight: 200
        - asset: assets/fonts/CabinetGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/CabinetGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/CabinetGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/CabinetGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/CabinetGrotesk-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/CabinetGrotesk-Black.ttf
          weight: 900

  uses-material-design: true

# Native splash config lives in flutter_native_splash.yaml (project root).
