<?php

namespace App\Enums;

use App\Enums\Concerns\HasValues;

/**
 * Where a folio line came from (D-04). The first three are generated by
 * GenerateFolioAction and reconciled on every refresh; MANUAL and CREDIT are
 * posted by staff and never touched by regeneration.
 *
 * Values match the strings already stored in `folio_items.source_type`. The
 * column is deliberately NOT cast to this enum: existing callers compare it
 * with plain strings.
 */
enum FolioItemSource: string
{
    use HasValues;

    case RESERVATION     = 'reservation';
    case SERVICE_BOOKING = 'service_booking';
    case SERVICE_REQUEST = 'service_request';
    case MANUAL          = 'manual';
    case CREDIT          = 'credit';

    /** @return list<string> the values GenerateFolioAction owns */
    public static function generated(): array
    {
        return [self::RESERVATION->value, self::SERVICE_BOOKING->value, self::SERVICE_REQUEST->value];
    }

    public function isGenerated(): bool
    {
        return in_array($this->value, self::generated(), true);
    }
}
